export const SCREEN_A = "SCREEN_A"; 
export const SCREEN_B = "SCREEN_B"; 
export const SCREEN_C = "SCREEN_C"; 
export const LOGIN = "LOGIN"; 
export const REGISTER = "REGISTER"; 
// export const SCREEN_A = "SCREEN_A"; 
// export const SCREEN_A = "SCREEN_A"; 
// export const SCREEN_A = "SCREEN_A"; 
// export const SCREEN_A = "SCREEN_A"; 